# application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employeeprofile-service
          uri: http://localhost:8082
          predicates:
            - Path=/employees/**
        - id: attendance-service
          uri: http://localhost:8081
          predicates:
            - Path=/attendances/**
        - id: recruitment-service
          uri: http://localhost:8083
          predicates:
            - Path=/candidates/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
