# Spring Boot configuration for production environment
spring:
  datasource:
    url: jdbc:postgresql://production-db-host:5433/hrms_production #db
    username: postgres
    password: production_password # change the password
    driver-class-name: org.postgresql.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    org.springframework: info
    org.hibernate: warn
