spring:
  profiles:
    active: development

# Common configuration settings
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
server:
  port: 8080
springdoc:
  enable-spring-security: false
