spring:
  profiles:
    active: development

# Common configuration settings
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
