management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/hrms?serverTimezone=UTC
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  # JPA and Hibernate #####
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        hbm2ddl:
#          auto: update
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
# Spring Boot configuration
spring:
  profiles:
    active: development
  # Security configuration
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5433/hrms
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
  # JPA properties
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port