server:
  port: 8080
  servlet:
    context-path: /hrms

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms?serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  # JPA and Hibernate #####
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
        show_sql: true
        use_sql_comments: true
        format_sql: true



