
scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['127.0.0.1:8081']


#metrics:
#  global:
#    scrape_interval: 60s
#  configs:
#    - name: hosted-prometheus
#      scrape_configs:
#        - job_name: node
#          static_configs:
#            - targets: ['localhost:9100']
