server:
  port: 8084

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          custom-client:
            provider: spring
            client-id: my-client-id
            client-secret: my-client-secret
            authorization-grant-type: client_credentials
            scope: read,write
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084

app:
  jwtSecret: ${JWT_SECRET:defaultsecret}

user-service:
  url: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG
