server:
  port: 8084

spring:
  application:
    name: auth-service
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000
      refresh-token:
        expiration: 604800000

  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Updated dialect
    show-sql: false

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      username: ${spring.security.user.name:eureka}
      password: ${spring.security.user.password:password}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  enable-spring-security: true

logging:
  level:
    root: INFO
    et.hrms: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG