server:
  port: 8084

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/authdb?useSSL=true&serverTimezone=UTC
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:password}
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          client-id: ${OAUTH_CLIENT_ID:myclient}
#          client-secret: ${OAUTH_CLIENT_SECRET:secret}
#        issuer: http://auth-server:8084
#        token:
#          access-token-time-to-live: 15m
#          refresh-token-time-to-live: 30d
  spring:
    security:
      oauth2:
        authorizationserver:
          client:
            client-id: myclient
            client-secret: secret
          issuer: http://auth-server:8084
          token:
            access-token-time-to-live: 15m
            refresh-token-time-to-live: 30d

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized